"""Add column last_name to User model

Revision ID: d4f5c4a9a069
Revises: a486f92bccf8
Create Date: 2025-04-04 05:49:19.872258

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd4f5c4a9a069'
down_revision = 'a486f92bccf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
