name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: changethis
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install --upgrade pip
          pip install .
          pip install .[dev]

      - name: Run tests
        working-directory: backend
        env:
        POSTGRES_SERVER: localhost
        POSTGRES_DB: app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: changethis
        run: |
          pytest -v --maxfail=1 --disable-warnings      

  docker-push:
    needs: backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t nimeshpandey16/fitness_backend:latest ./backend
          docker push nimeshpandey16/fitness_backend:latest
